spring.application.name=bratus
server.port=8080
spring.h2.console.enabled=true
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:h2:mem:holidayhouse;DB_CLOSE_DELAY=-1}
spring.jpa.hibernate.ddl-auto=update

airbnb.ical.url=${AIRBNB_ICAL_URL:https://www.airbnb.com/calendar/ical/51274533.ics?s=9cae2709918047b72724f0831f2f458d}

spring.security.user.name=mojeIme
spring.security.user.password=mojaLozinka

debug=true

# The email to receive inquiries
inquiry.recipient.email=${INQUIRY_EMAIL:andrijasevic.ante53@gmail.com}

# Disable OSIV to avoid potential persistence issues
spring.jpa.open-in-view=false

# Static resource configuration
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

# Don't use Thymeleaf caching in development
spring.thymeleaf.cache=false

# Show more error details
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:andrijasevic.ante53@gmail.com}
spring.mail.password=${MAIL_PASSWORD:edta pcym qhlo hwoi}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

heroku config:set MAIL_USERNAME=andrijasevic.ante53@gmail.com
heroku config:set MAIL_PASSWORD=nanqyf-bihris-2kyZdy